name: graph_explorer
description: A versatile library for generating and analyzing graphs with support for JSON and ASCIIArtTree.
version: 1.0.1
repository: https://github.com/gmpassos/graph_explorer

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  collection: ^1.17.0

dev_dependencies:
  lints: ^1.0.1
  dependency_validator: ^3.2.2
  test: ^1.21.4
  coverage: ^1.2.0
